[tool.poetry]
name = "mwe"
version = "0.1.0"
description = ""
authors = ["Felipe Cetrulo <fecetrulo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
kapitan = "^0.32.0"
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
